### ISSUE TITLE
-i does not work on unicode?

### ISSUE THREAD

**Issue by jeekl** [beyondgrep/ack1#100]
When trying to match non-latin characters like the Swedish åäö, it seems that -i does not work.

<pre>
$ cat testfile
åäö
Åäö
test
Test
$ ack åäö testfile 
åäö
$ ack Åäö testfile 
Åäö
$ ack -i Åäö testfile 
Åäö
$ ack -i test testfile 
test
Test
</pre>

This is with App::Ack 1.90 from CPAN on perl 5.10.

**Comment by hoelzro** [comment]
Reported in ack2 as https://github.com/petdance/ack2/issues/297.
