### ISSUE TITLE
No inverse of -G

### ISSUE THREAD

**Issue by jjl** [beyondgrep/ack1#108]
It would be nice to exclude a file (e.g. I currently want to exclude *.sql) without having to limit it to a range of file extensions (the system I'm using appears to have a variety to choose from).

What I eventually came up with was -G '(?<!.sql)$' which is quite ugly. There should be a better way.

**Comment by petdance** [comment]
What would that better way look like?

Also, --sql is already defined.

**Comment by jjl** [comment]
-E '.sql$'     is what I was thinking, assuming you pick -E (which I just went for because it symbolises 'exclude' and -g is taken)

And yes, I take your point about --sql being defined, but say I have a bunch of php files and I know it was defined in either a .php or .phtml file, but other php extensions would clog it up with a load of useless output, there's no easy way to do that apart from --type-set (which is frustrating since it's a one-time op I'm trying to use.

It came about largely because I'm working with drupal at the moment and I hadn't set up a type for drupal php files in my ackrc. I wanted everything, except the sql file which had whitespace removed and was clogging up my output.

**Comment by petdance** [comment]
There is now --invert-file-match.  I trust this does what you want.
