### ISSUE TITLE
Printing help and the .ackrc file

### ISSUE THREAD

**Issue by whumann** [beyondgrep/ack1#110]
When I started using ack, typing "ack" without options would print the help. Good! 

Now I have an .ackrc file and typing "ack" results in 

"ack: No regular expression found". 

I would prefer if ack would distinguish between command line args and .ackrc args and still print the help when called without args.

**Comment by diego898** [comment]
I also agree with issue. It was discussed on the google groups some time ago.

I changed this locally by moving the if block responsible for printing the help, above the block responsible for adding the ackrc contents to the ARGV array

**Comment by mmcclimon** [comment]
This has been fixed in [ack 2](http://github.com/petdance/ack2)
