### ISSUE TITLE
return code and pager issues when piping data to ack

### ISSUE THREAD

**Issue by gautambt** [beyondgrep/ack1#111]
I just started using ack (version 1.92) and noticed the following when piping data through ack:

1) The return value is always zero (even if there are no matches). The man page says the return value is 1 when there are no matches.
2) The --pager option and the ACK_PAGER option do not work.

**Comment by petdance** [comment]
Please write these up as two separate tickets.  They are not the same problem.

Also, please give details about "do not work" for the pager problem.  I don't know what "do not work" means specifically.

Thank you.
