### ISSUE TITLE
Return code does not work when piping data through ack

### ISSUE THREAD

**Issue by gautambt** [beyondgrep/ack1#112]
The return value is always zero (even if there are no matches). The man page says the return value is 1 when there are no matches.

For example echo Foo|ack Bar does not return 1

**Comment by fallwith** [comment]
I took a stab at fixing this:

http://github.com/fallwith/ack/commit/20d372e9f414dd02a7c84225edcc0cd0a75e3cc0

**Comment by gautambt** [comment]
That fixes it, thanks.

**Comment by hoelzro** [comment]
This is fixed as of ack2.
