### ISSUE TITLE
--pager option does not work when piping data through ack

### ISSUE THREAD

**Issue by gautambt** [beyondgrep/ack1#113]
The --pager option and the ACK_PAGER option do not work when piping data through ack. In the following cases the output is not piped through less:

$echo Foo|ack Foo --pager="less -r"
$export ACK_PAGER="less -r"
$echo Foo|ack Foo

**Comment by CharString** [comment]
What I'd like to know is why I have to set ACK_PAGER, while man and other programs just use PAGER.

Can't ack just use PAGER if ACK_PAGER is not set?

**Comment by hoelzro** [comment]
Migrated to ack2 queue.
