### ISSUE TITLE
For V 1.90: --type-add perl=.psgi works on command line, not in .arkrc

### ISSUE THREAD

**Issue by ronsavage** [beyondgrep/ack1#114]
Hi Andy

ack is a marvellous app, but there's just one thing...

If I use --type-add perl=.psgi in .ackrc I get:
ron@zephyr:~/Plack-0.9913/eg$ ack Plack::Builder
Unknown option: type-add perl
ack: See ack --help or ack --man for options.
Note: .ackrc also contains:
--ignore-case
--nocolor
But on the command line, it's ok:
ron@zephyr:~/Plack-0.9913/eg$ ack --type-add perl=.psgi Plack::Builder
dot-psgi/static.psgi
1:use Plack::Builder;

That reminds me: I'd like to see *.psgi recognised as a standard Perl file.
TIA.

**Comment by petdance** [comment]
This is a bug in putting stuff in the .ackrc.  I think you have to do it as --type-add\nperl=.psql, where \n is an actual linefeed.
