### ISSUE TITLE
support taking regex from external source

### ISSUE THREAD

**Issue by adavies42** [beyondgrep/ack1#116]
ack should be able to accept a regex from a file (or stdin), much like grep's "--file" option.

**Comment by mlsquires** [comment]
I just noticed that ack didn't have this. It's handy to build up some patterns in a file rather than editing the command line arguments.

**Comment by petdance** [comment]
Can you give an example of how this would work for you?  What would this file look like?  Do you have real-world examples for us to look at?

**Comment by mlsquires** [comment]
For grep, I can prepare a file that looks like this:
logger\s*=
FunkyLogger
createLogger

with one regexp per line. Then I use 'grep --file pats.txt ...'  to have it use those patterns. It's equivalent to 'logger\s*=|FunkyLogger|createLogger' but easier to deal with.

**Comment by petdance** [comment]
Aha, so the "from a file" is secondary to "ORing a bunch of patterns together."

This definitely won't happen in ack 1.x, but maybe in ack 2.1 we'll think about it.  I'll migrate this issue over to that queue.

**Comment by hoelzro** [comment]
Migrated to ack2 queue.
