### ISSUE TITLE
option to ignore svn:ignored files...

### ISSUE THREAD

**Issue by coke** [beyondgrep/ack1#118]
... and/or only search files under version control. =-)

be fine as a plugin, since not everyone cares about svn.

use case: avoid searching files generated during your build (generated code, makefiles generated from templates, etc.)

**Comment by petdance** [comment]
The same would also apply to .gitignore, too.

**Comment by chocolateboy** [comment]
... and .git/info/exclude...

**Comment by petdance** [comment]
This will have to be done with plugins in ack 2.
