### ISSUE TITLE
bug:ack.pl mangles cmd window fg and bg on MS Windows

### ISSUE THREAD

**Issue by rfulbrig** [beyondgrep/ack1#121]
my cmd window properties are: white bg and black text
after ack.pl runs, the colors are reversed: black bg and white text
ack.pl should leave the cmd window properties intact.

**Comment by dwierenga** [comment]
this happens for me as well.

**Comment by hoelzro** [comment]
I'll assume this is fixed as of ack2; if not, please file an issue under the ack2 issues queue.
