### ISSUE TITLE
Only use the --pager option when the lines of output are greater than the terminal height

### ISSUE THREAD

**Issue by tsibley** [beyondgrep/ack1#140]
With this enhancement, ack's pager option would be much more useful.  git does similar smart paging logic.

**Comment by petdance** [comment]
I don't see how this could work unless we buffered the lines of output before printing them.

ack cannot buffer its output before printing, because then people cannot see results on searches that take a long time.

**Comment by tsibley** [comment]
I agree that buffering would be required and that buffering all the time isn't desired.

Perhaps this behaviour could be turned on by an option (--smart-paging or something).  With the option enabled, ack would buffer lines only up to the terminal height.  As soon as the buffer grew larger than the terminal height, it would be flushed to the pager and subsequent lines wouldn't be buffered.

I guess the alternative is to use a pager that does this for me...

**Comment by tsibley** [comment]
Ah, nevermind!  A careful reading of less(1) led me to --pager="less -XFR" which auto-quits if the content fits the screen and doesn't clear the screen upon exit.  Sorry to bother.

**Comment by blixtor** [comment]
The "less -XFR" trick might be worth a mention in the docs, though?! Thanks tsibley!

**Comment by petdance** [comment]
Yes, a mention in the docs would be great.  Someone please do that and get me the patch / pull request.

**Comment by tsibley** [comment]
Emailed.
