### ISSUE TITLE
Improve speed by reduce stat syscall

### ISSUE THREAD

**Issue by kcwu** [beyondgrep/ack1#149]
This is idea to improve file search speed.

Currently, ack use File::Next to search files.
It will stat each entry inside directory, to determine it is file or directory.
After File::Next know the entry is normal file (via -f), it will callback to ack's file_filter.

If we assume directory name won't look like file, it is possible to speed up:
1. Check entry name first. If the name is recognized by ack, but isn't interested by this search, we can just ignore such entry.
2. Only test it's file/dir/link if the name is not recognized by ack.

However, it may accident ignore directories with name recognized by ack. So this feature may need a option to let user turn on/off.

**Comment by kcwu** [comment]
By the way, linux's readdir(3) return "d_type" which specify a entry is directory or not. Thus save a lot of stat(2) calls.

Linux's find(1) takes this advantage and is much faster. I don't know how to apply this trick in perl though.

**Comment by hoelzro** [comment]
Migrated to ack2 queue.

**Comment by petdance** [comment]
This issue was moved to petdance/ack3#44
