### ISSUE TITLE
Markdown files and Readmes

### ISSUE THREAD

**Issue by allan** [beyondgrep/ack1#150]
I'd like to see all files ending with `.md`, `.mkd`, `.markdown` and all _Readme_'s (whitout any extension) added to the files that are searched when no extra option is given.

**Comment by jm3** [comment]
+1

**Comment by jm3** [comment]
I would be happy to implement this if there are any pointers anyone can direct me toward.  `--type-set text=md` and `--type-add text=md` both fail with the error, _Builtin type "text" cannot be changed._

**Comment by hoelzro** [comment]
I can't speak for @petdance, but he would probably say that this will be doable in ack2.  For the time being, you can add the following to your .ackrc to get --markdown to work, and also to add .md files to the list of files considered by default:

```
--type-set markdown=.md
```

**Comment by petdance** [comment]
@allan The key is that ack 1.x is designed to only search source code.  Markdown and READMEs aren't source code.  Ack 2.x will be more forgiving.

**Comment by petdance** [comment]
Text opening behavior has changed in ack 2.
