### ISSUE TITLE
runaway memory usage on large directory lists

### ISSUE THREAD

**Issue by ghost** [beyondgrep/ack1#151]
I recently ran ack over a codebase in which (previously unbeknownst to me) one directory contained a couple GB of temp files. After a few hours of grinding it's wheels it crashed the system by using all available memory. My presumption (I don't have time to look into it) is that ack or File::Next is using readdir in array context. Anyway, this is a problem making ack effectively unusable in this or any similar situation.

**Comment by petdance** [comment]
Do you know how many files were in the directory?  You say a couple GB, but how many file entries?

**Comment by ghost** [comment]
I'm not completely certain , but based on experience with other parts of the application I suspect at least several million.

**Comment by hoelzro** [comment]
Migrated to ack2 queue.
