### ISSUE TITLE
Add --also-in-file functionality

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#153]
Right now, to find a match in a file that also has another match, you do this

ack manualtitles $(ack -l bookbag)

Which is a pain, and can run afoul of the shell, and doesn't work for Windows people.

Instead, we should do this, roughly:

ack manualtitles --also-in-file bookbag

**Comment by djanowski** [comment]
Would it be possible/make sense to use the existing `--match` switch? Maybe for multiple matches one could do:

```
$ ack --match manualtitle --match bookbag
```

**Comment by petdance** [comment]
On May 15, 2011, at 8:26 PM, djanowski wrote:

> Would it be possible/make sense to use the existing `--match` switch? Maybe for multiple matches one could do:
> 
>    $ ack --match manualtitle --match bookbag

Not sure about semantics, but it's definitely not going in until 2.0.

xoa

## 

Andy Lester => andy@petdance.com => www.techworklove.com => AIM:petdance

**Comment by hoelzro** [comment]
Migrated to ack2 queue.
