### ISSUE TITLE
Failed test 'ignore relative paths instead of just directory names'

### ISSUE THREAD

**Issue by romary22** [beyondgrep/ack1#157]
Version :Active perl 5.12.2
OS : Windows XP SP3

The install of App::Ack 1.94 with cpan fails on make test :
t/ack-ignore-dir.t ........ 21/26
#   Failed test 'ignore relative paths instead of just directory names'.<br>
#   at t/ack-ignore-dir.t line 147.<br>
# +----+----------------------------------------+----+--------------------------------+<br>
# | Elt|Got                                     | Elt|Expected<br>
# +----+----------------------------------------+----+--------------------------------+<br>
# \*   0|t\swamp\groceries\another_subdir\fruit  \*    |                                |<br>
# \*   1|t\swamp\groceries\another_subdir\junk   \*    |                                |<br>
# |   2|t\swamp\groceries\fruit                 |   0|t\swamp\groceries\fruit         |<br>
# |   3|t\swamp\groceries\junk                  |   1|t\swamp\groceries\junk          |<br>
# |   4|t\swamp\groceries\subdir\fruit          |   2|t\swamp\groceries\subdir\fruit  |<br>
# |   5|t\swamp\groceries\subdir\junk           |   3|t\swamp\groceries\subdir\junk   |<br>
# +----+----------------------------------------+----+--------------------------------+<br>
# Looks like you failed 1 test of 26.<br>
t/ack-ignore-dir.t ........ Dubious, test returned 1 (wstat 256, 0x100)<br>
Failed 1/26 subtests<br>

The solution is to correct the path on line 143 in ack-ignore-dir.t
from         [ '--ignore-dir=t/swamp/groceries/another_subdir', ],
to             [ '--ignore-dir='  . File::Spec->catdir('t' ,'swamp', 'groceries' , 'another_subdir'), ],

**Comment by petdance** [comment]
Thanks, I've fixed this on master.
