### ISSUE TITLE
ack erroneously goes into filter mode

### ISSUE THREAD

**Issue by tstgruby** [beyondgrep/ack1#158]
ack --help says:

> ack may also search STDIN, but **only** if no FILE are specified, or if
> one of FILES is "-".

When specifying an argument on the command line (and actually running ack as a subprocess on Windows), it says:

> Ignoring 1 argument on the command-line while acting as a filter.

How about checking the condition the help was talking about:

```
if ( App::Ack::input_from_pipe() && scalar(@ARGV) == 0 ) {
```

\edit: sort of a duplicate of #106

**Comment by lloeki** [comment]
Workaround: https://github.com/petdance/ack/issues/106#issuecomment-5065852

**Comment by gedge** [comment]
I have to agree with tstruby on the title and validity of this issue.

On my (linux bash) shell, I get the same "Ignoring..." warning, which is counter-intuitive (and not grep-compatible), in the following:

```
grep foo bar.txt | while read foo; do ack $foo snafu.txt;done
```

This is broken - to fix, I use the workaround:

```
grep foo bar.txt | while read foo; do ack $foo snafu.txt < /dev/null ;done
```

Fugly.

**Comment by hoelzro** [comment]
Migrated to ack2 queue.
