### ISSUE TITLE
Feature request: single-line files just report match or not, if they are big

### ISSUE THREAD

**Issue by epa** [beyondgrep/ack1#159]
Various programs produce text files all on a single line.  These files can be quite big.  If you search them with ack and it finds a match, then it prints the whole file contents.

If a file has just a single line and that line is more than, say, 1000 characters long, then ack should suppress its normal printout of matching lines and just say 'Single-line text file X matches'.

**Comment by hoelzro** [comment]
Migrated to ack2 queue.
