### ISSUE TITLE
Can't use type-add with files that have suffixes containing '.'

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#16]
<b>What steps will reproduce the problem?</b>
1. Specify '--type-add=perl=.pm.in' in .ackrc
2. Search for a string contained in a file with the '.pm.in' extension
3. String is not found.

What is the expected output?

(String found in Foo.pm.in)

What do you see instead?

No output -- string not found. It works fine when I specify '.in' instead,
so I'm assuming it's the embedded '.' that's messing things up.

What version of the product are you using?

From the repo that I just built, 'App::Ack 1.89_02, File::Next 1.02, Perl
5.008008, /usr/bin/perl'

On what operating system?

Ubuntu -- 'Linux foobar 2.6.24-22-generic #1 SMP Mon Nov 24 18:32:42 UTC
2008 i686 GNU/Linux'

<b>Please provide any additional information below.</b>

ack -f doesn't see the file when I try to add the type '.pm.in', so it
seems it's the file matching that's the problem. The 'in' suffix is from
autoconf which we use to building files that are actually installed.

I have a workaround, but it would be cool to get this fixed. I have the
latest repo and would be happy to produce a patch, but I haven't identified
where in the code this should happen. I'll dig further.

Reported by talexb at 2009-07-14 15:07:SImported from Google Code issue number 149

**Comment by evocateur** [comment]
Similarly, it is impossible to filter out minified resources that use a <code>*.min.{css,js}</code> or <code>*-min.{css,js}</code> pattern. This would be really great, as the output of matches in minified files (all one line) tends to kersplode across the terminal output.

Thanks!
