### ISSUE TITLE
Install issues on Strawberry Perl

### ISSUE THREAD

**Issue by dhorne** [beyondgrep/ack1#162]
Hi, I encountered one test failure when installig Ack

Stawberry Perl banner:

```
----------------------------------------------
 Welcome to Strawberry Perl Portable Edition!
 * URL - http://www.strawberryperl.com/
 * see README.portable.TXT for more info
----------------------------------------------
Perl executable: U:\bin\myperl\perl\bin\perl.exe
Perl version   : 5.12.2

Microsoft Windows XP [Version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.
```

Failure:

```
t/ack-ignore-dir.t ........ 25/26
#   Failed test 'ignore relative paths instead of just directory names'
#   at t/ack-ignore-dir.t line 147.
# +----+----------------------------------------+----+--------------------------
------+
# | Elt|Got                                     | Elt|Expected
      |
# +----+----------------------------------------+----+--------------------------
------+
# *   0|t\swamp\groceries\another_subdir\fruit  *    |
      |
# *   1|t\swamp\groceries\another_subdir\junk   *    |
      |
# |   2|t\swamp\groceries\fruit                 |   0|t\swamp\groceries\fruit
      |
# |   3|t\swamp\groceries\junk                  |   1|t\swamp\groceries\junk
      |
# |   4|t\swamp\groceries\subdir\fruit          |   2|t\swamp\groceries\subdir\f
ruit  |
# |   5|t\swamp\groceries\subdir\junk           |   3|t\swamp\groceries\subdir\j
unk   |
# +----+----------------------------------------+----+--------------------------
------+
# Looks like you failed 1 test of 26.
t/ack-ignore-dir.t ........ Dubious, test returned 1 (wstat 256, 0x100)
```

**Comment by csjewell** [comment]
I see this one, too, and it's making installers with Padre a pain.

**Comment by nyet** [comment]
It seems that the script barf when testing 'ignore relative paths instead of just directory names' and this is the code that runs ok on my Win32 box (no Cygwin).

DASH_IGNORE_DIR_IGNORES_RELATIVE_PATHS: {
       if ($^O eq 'MSWin32') {
               set_up_assertion_that_these_options_will_ignore_those_directories(
                       [ '--ignore-dir=t\swamp\groceries\another_subdir', ],
                       [ @std_ignore, 'another_subdir',                   ],
                       'ignore relative paths instead of just directory names',
               );
       }
       else {
               set_up_assertion_that_these_options_will_ignore_those_directories(
                       [ '--ignore-dir=t/swamp/groceries/another_subdir', ],
                       [ @std_ignore, 'another_subdir',                   ],
                       'ignore relative paths instead of just directory names',
               );
       }
   sets_match( \@results, \@expected, $test_description );
}

**Comment by petdance** [comment]
Windows install should work better under ack 2.  If there continue to be problems, please report them at https://github.com/petdance/ack2
