### ISSUE TITLE
Ignore files by pattern / --ignore-pattern

### ISSUE THREAD

**Issue by blueyed** [beyondgrep/ack1#164]
I would like to ignore some files by pattern, e.g. `^bundle__.*\.js$`, but that does not appear to be possible.

A good enough workaround (for my situation) appears to be issue #142 (pull request) to make ack ignore *.min.js files; I then would change the name of the bundles to *.min.js.

However, it's very useful to add your own file pattern for exclusion, so I wonder if I am missing something.. - I can only find "--ignore-dir".

**Comment by petdance** [comment]
These will all be addressed in ack 2.0, currently under development.

**Comment by blueyed** [comment]
Thanks. I can work around this currently by using --ignore-dir=cache, which is useful anyway.
