### ISSUE TITLE
matches are hidden for certain patterns on files with dos line-endings

### ISSUE THREAD

**Issue by permanuno** [beyondgrep/ack1#165]
two files, one with unix line-endings, the other with dos line-endings:

<pre>
sergio@pisco $ echo "proc_upload_import();" > unix.txt
sergio@pisco $ perl -pe 's/\n/\r\n/' unix.txt > dos.txt
</pre>

with no options, match in dos.txt is hidden:

<pre>
sergio@pisco $ ./ack 'proc_.*import.*()' dos.txt unix.txt 
dos.txt

unix.txt
1:proc_upload_import();
</pre>

with --nocolor, match shows:

<pre>
sergio@pisco $ ./ack --nocolor 'proc_.*import.*()' dos.txt unix.txt 
dos.txt
1:proc_upload_import();

unix.txt
1:proc_upload_import();
</pre>

also like this:

<pre>
sergio@pisco $ ./ack 'proc_.*import.*()' dos.txt unix.txt | cat -
dos.txt:1:proc_upload_import();
unix.txt:1:proc_upload_import();
</pre>

Info about my system (Ubuntu 10.10, bash, urxvt)

<pre>
sergio@pisco $ ls -a ~/.ackrc
ls: cannot access /home/sergio/.ackrc: No such file or directory

sergio@pisco $ ./ack --version
ack 1.94
Running under Perl 5.10.1 at /usr/bin/perl

Copyright 2005-2010 Andy Lester.

This program is free software.  You may modify or distribute it
under the terms of the Artistic License v2.0.

sergio@pisco $ uname -a
Linux pisco 2.6.35-28-generic-pae #49-Ubuntu SMP Tue Mar 1 14:58:06 UTC 2011 i686 GNU/Linux

sergio@pisco $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 10.10
Release:    10.10
Codename:   maverick

sergio@pisco $ echo $BASH_VERSION
4.1.5(1)-release

sergio@pisco $ rxvt-unicode --version 2>&1 | grep rxvt-unicode
rxvt-unicode (urxvt) v9.07 - released: 2009-12-27
</pre>

ps. i know the pattern is weird.  i actually wanted this: `proc_.*import.*\(\)`

**Comment by permanuno** [comment]
possibly related to petdance/ack#83

**Comment by hoelzro** [comment]
Fixed in ack2.
