### ISSUE TITLE
Case Insensitive Filename Search

### ISSUE THREAD

**Issue by askedrelic** [beyondgrep/ack1#167]
I am looking to figure out how to perform a case insensitive filename search with ack. The find command's case insensitive name search is what I am hopefully trying to replicate in ack: `find . -iname "*foo*"`

As the changelog for 1.77_3 states, the `-i` flag was removed from working with the file search flag, `-g`
https://github.com/petdance/ack/blob/master/Changes#L353
`--smart-case` doesn't seem to apply either to filename search.

Is there something I am missing?

Examples: 

<pre>
ruin:/tmp/ack-test$ ls
FooBuzz.pl  foo.pl      fooBAR.pl
ruin:/tmp/ack-test$ ack -g "foo"
foo.pl
fooBAR.pl
ruin:/tmp/ack-test$ ack -i -g "foo"
foo.pl
fooBAR.pl
ruin:/tmp/ack-test$ ack --smart-case -g "foo"
foo.pl
fooBAR.pl
ruin:/tmp/ack-test$ find . -iname "*foo*"
./foo.pl
./fooBAR.pl
./FooBuzz.pl
</pre>

**Comment by petdance** [comment]
I think I'm going to hold off on fixing this in 1.x, especially if I pulled it out originally.  Filename matching is going to be a good deal more flexible in 2.0.  (petdance/ack2 if you're interested)

**Comment by askedrelic** [comment]
Thanks for the reply! I did not know there was a 2.0 in the works, I will keep an eye on that and see what occurs. I'll close this issue for now.
