### ISSUE TITLE
-w should wrap the regex with \b(?:...)\b, not just \b...\b

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#169]
From Bob Kleeman:

I would expect the output on that one to be just foo and bar, without
foobar or barfoo.  Or to put into English what I think "ack -w
'(foo|bar)'" should be doing:  search for lines with the whole-word
foo or the whole-word bar, and print them out.  I would expect similar
behavior if the pattern were 'foo|bar' or '(foo|bar)'.  And if I
wanted the behavior of "accept words that begin with foo or end with
bar", I'd expect to have to specify that explicitly: "ack
'\bfoo|bar\b'".

Additionally, I don't understand why "ack -w 'foo|bar'" rejects
barfoo, but "ack -w '(foo|bar)'" accepts it.

**Comment by hoelzro** [comment]
Migrated to ack2.
