### ISSUE TITLE
-A (and maybe -B) should accept a regex

### ISSUE THREAD

**Issue by tsibley** [beyondgrep/ack1#170]
It's often very useful to print context lines (especially after) until a regex matches.  I imagine syntax like: `ack -A /^}/ 'sub foo'` in order to inspect all the subs named foo in your source.

I see less use cases for before context, but it may make sense to keep the options symmetrical.

**Comment by petdance** [comment]
Thanks for submitting.  Some of the notes from the thread might be good to add on here.  I won't do anything with this until ack 2.0, but it's good to keep in mind.

**Comment by tsibley** [comment]
Which thread?

**Comment by petdance** [comment]
The thread in ack-users.

**Comment by hoelzro** [comment]
I've mentioned this in a similar issue in the ack2 queue; closing.
