### ISSUE TITLE
ack --man doesn't use regular dashes for switches

### ISSUE THREAD

**Issue by djanowski** [beyondgrep/ack1#171]
This means one can't do `ack --man` and `/-a` to search for a specific switch. Not sure what character it's rendering, but it's also not an en or em dash.

**Comment by petdance** [comment]
On May 15, 2011, at 8:24 PM, djanowski wrote:

> This means one can't do `ack --man` and `/-a` to search for a specific switch. Not sure what character it's rendering, but it's also not an en or em dash.

It's just how Pod::Usage does it.

It seems I can pass a -noperldoc => 1 arg to Pod::Usage::usage and it prints out simple text format via Pod::Text, but then you lose all the other formatting.  

xoa

## 

Andy Lester => andy@petdance.com => www.techworklove.com => AIM:petdance

**Comment by hoelzro** [comment]
This is working for me in ack2, so if you still have this problem, please let us know and we can discuss it in the ack2 queue!
