### ISSUE TITLE
Implement grep's -e PATTERN, --regexp=PATTERN

### ISSUE THREAD

**Issue by jnareb** [beyondgrep/ack1#173]
Currently to specify regexp that looks like option specifier i.e. beginning with '-', e.g. when searching for '-pg', one has to use

```
ack -- -pg
```

It would be nice if ack implemented -e PATTERN / --regexp=PATTERN that GNU grep uses.

**Comment by brucewoodward** [comment]
The option that you are after is --match

**Comment by jnareb** [comment]
Well, it would be nice to have `-e` / `--regexp` as an alias to `--match` to be interface-compatibile with GNU grep.

**Comment by hoelzro** [comment]
@jnareb ack isn't really meant to be interface-compatible with grep, but I'm migrating this to the ack2 queue, so we can discuss it there.
