### ISSUE TITLE
Add no-ignore-case option

### ISSUE THREAD

**Issue by dtb** [beyondgrep/ack1#182]
I would like a --no-ignore-case option that overrides --ignore-case. Use case: I almost always want to ignore case differences, so my `.ackrc` has `-i` set. Occasionally though, I want to search case sensitive. Currently, my only option is to edit my `.ackrc`. 

There are other options like this (e.g., `--nopager`), so it seems reasonable.

If I ever become less lazy, I'll probably send a pull request.

**Comment by petdance** [comment]
Yes, we should definitely have --no-ignore-case.

Also, have you looked at --smart-case?  There is a --no-smart-case option, because I have to use it sometimes because I have --smart-case in my ~/.ackrc.

**Comment by hoelzro** [comment]
Mentioned in corresponding ack2 issue.
