### ISSUE TITLE
How do we handle upper vs. lower-case extensions?

### ISSUE THREAD

**Issue by Tux** [beyondgrep/ack1#193]
I want .U (from perl's metaconfig) to fall into .SH category, so in my ~/.ackrc I had

--type-add=shell=.U

but to no avail, as it should be lower case.

--type-add=shell=.u

works, but also adds .u with a lower case u extension to the shell syntax list, which is not correct, as .u files in my development environment are something completely different than .U

**Comment by hoelzro** [comment]
Migrated to the ack2 queue.
