### ISSUE TITLE
multiple patters on same line in random order

### ISSUE THREAD

**Issue by Tux** [beyondgrep/ack1#194]
Something to be able to ack on multiple words on the same line in whatever order, so that (suggestion)

$ ack -i -w -e run -e like -e hell

=>

  m{(?=._\b run \b)(?=._\b like \b)(?=.*\b hell \b)}xi

which is no fun typing from the command line

**Comment by hoelzro** [comment]
This is in the ack2 queue as https://github.com/petdance/ack2/issues/139.
