### ISSUE TITLE
Faulty header line not conform perl specs

### ISSUE THREAD

**Issue by Tux** [beyondgrep/ack1#195]
ack is as far as I can see the _only_ app that installs the ack script with the wrong header line
# !/usr/bin/env perl

All other installations respect what is chosen in perl's $Config{startperl}

This is especially annoying when you have over 50 perls available and you are testing a perl that comes first in the $PATH that does not work with ack.

Please follow $Config{startperl}. It is there for a very valid purpose!

**Comment by sfavre** [comment]
For standalone use, I prefer the following. (First line is blank.) It's long, but it is pretty universal.

```

## Do not remove this line
eval '(exit $?0)' && eval 'exec perl -wS $0 ${1+"$@"}'
        && eval 'exec /usr/bin/perl -wS $0 $argv:q'
                if $running_under_some_shell;

## Just here to suppress a warning:
$running_under_some_shell = 0;
```

**Comment by hoelzro** [comment]
Migrated to ack2 queue.
