### ISSUE TITLE
new filetypes

### ISSUE THREAD

**Issue by lazylester** [beyondgrep/ack1#196]
suggestions for inclusion in 2.0:
.coffee (coffeescript)
.haml (haml)
.sass (sass)
.ejs (embedded javascript template)

**Comment by mat813** [comment]
I'll add .scss which is another flavor for .sass files.

**Comment by rromanchuk** [comment]
+1 I think these are pretty critical defaults

**Comment by chelmertz** [comment]
+1, .json could be considered as well.

**Comment by chelmertz** [comment]
Or really, --no[whatever] could exclude all filenames with the .[whatever] ending. There would still be a need for listing include:able filetypes though, unless the syntax would be changed to --i[whatever] or something else that could be differentiated from --man etc.

**Comment by SethTisue** [comment]
+1 on CoffeeScript... though I don't really mind having to put `--type-add=js=.coffee` in my .ackrc, either.

**Comment by hoelzro** [comment]
Coffeescript and Sass have been added to ack 2.0; I've migrated this issue over there.
