### ISSUE TITLE
type-set=tags=TAGS (filename, not a filename extension)

### ISSUE THREAD

**Issue by PhilHudson** [beyondgrep/ack1#204]
If I put in my .ackrc the line:

type-set=tags=TAGS

and then run
# ack --help=types

I get:

```
...
--[no]sql          .sql .ctl
--[no]tags         .TAGS
--[no]tcl          .tcl .itcl .itk
...
```

It should say:

```
--[no]tags      TAGS  (no '.')
```

Running ack seems to confirm that the type-set is being treated as if it were ".TAGS" not "TAGS"

This is contrary to documentation, which shows explicit leading '.' characters for filename extensions throughout.

**Comment by petdance** [comment]
ack 1.x does not allow you to add a filetype that is just a filename, not an extension.  Ack 2.0, however, will give you much more flexibility in naming of your files.  Sorry that ack 1.x won't do it for you.  We have the same problem with Make files, too.

Why do you want to be able to say --tags anyway?  Or are you wanting to say --notags?  If you're saying --notags, then I'm guessing that you're using -a, and you probably shouldn't be.

**Comment by PhilHudson** [comment]
Your question pinpoints the real bug. I see I am in the hands of a resolution master. The _real_ bug is that 'ack --elisp' searches not only *.el but also TAGS. TAGS files contain data derived from and applicable to elisp code, but they are not themselves elisp. I think the built-in elisp type-set is buggy. Should I open another issue for that?

EDIT: nope, it's because I have --all in my .ackrc. I think.

**Comment by petdance** [comment]
I figured it was because of -a/--all.  Most filetype problems are because people put --all in their .ackrc, which is not what ack was meant to do.  It's meant as a last resort, not a default.  But the number of people who do it show that we needed to rethink filetypes, and was the genesis of ack 2.0.
