### ISSUE TITLE
Possible to filter on extensions containing a period?

### ISSUE THREAD

**Issue by jhoffmann** [beyondgrep/ack1#209]
I'm having an issue where I need to filter out *.lang.php files from ack results, though ack doesn't seem to want to filter on extensions containing a dot.

Example:

```
$ find . -type f -name '*.lang.php' | wc -l
    3787

$ ack -f --noenv --type-set lang=.lang.php --lang | wc -l
       0
```

Is this not possible?  Is the type matching done on on the filename after the last dot?

**Comment by petdance** [comment]
No, it's not possible to do this in ack 1.x.  ack 2.0 will allow it.

**Comment by jhoffmann** [comment]
Thanks PD.
