### ISSUE TITLE
Windows & UNC search

### ISSUE THREAD

**Issue by atatarn** [beyondgrep/ack1#215]
I'm trying to search in UNC path on Windows:

C:\Users\Insane>ack ans-msk \smpns.ural.local\Conf\
ack: \smpns.ural.local\Conf: No such file or directory

Is there any way to do it with ack?

**Comment by michaelgruenewald** [comment]
Apparently you have to escape the backslashes, e.g. `ack -fa \\\\server\\share` works for me.
