### ISSUE TITLE
Ignore minified css files (ala minified js files)

### ISSUE THREAD

**Issue by joelklabo** [beyondgrep/ack1#218]
This would ignore files with the extension: min.css , that's it.

**Comment by joelklabo** [comment]
https://github.com/petdance/ack/pull/219

**Comment by petdance** [comment]
Thanks for the pull request.

I'm wary of adding any new functionality to ack 1.x.  This has been hashed around a lot with .min.js as well.  Chances are I'm not going to do anything with this.

**Comment by joelklabo** [comment]
That's cool. I added it to my fork, just thought it was worth sharing.  

## 

Joel Klabo
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by petdance** [comment]
Yeah, thank goodness for everyone getting to keep their own forks.

ack 2.0 is going to be much more flexible in defining what you want and don't want.  Check it out at petdance/ack2 if you're interested.

**Comment by joelklabo** [comment]
I will. Thanks! 

## 

Joel Klabo
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by petdance** [comment]
This has been implemented in ack 2.
