### ISSUE TITLE
with modified time supports

### ISSUE THREAD

**Issue by fayland** [beyondgrep/ack1#222]
Hi

is it possible to add --mtime supports for modified time (-M in Perl). usually I just want to search the files which modified today or last week.

Thanks

**Comment by petdance** [comment]
I don't think we'll add it in ack 1.x, but it's possible in 2.0.  https://github.com/petdance/ack2/issues/35

**Comment by hoelzro** [comment]
Closing, as the issue has been copied to the ack2 queue.
