### ISSUE TITLE
ack opens large files regardless of type

### ISSUE THREAD

**Issue by CyberShadow** [beyondgrep/ack1#223]
Running this command on a slow network drive:

```
ack --php PATTERN
```

causes ack to open large dictionary files with an extension such as `.95`.

**Comment by petdance** [comment]
ack looks at the shebang line of files where it isn't able to determine a filetype.  This is to catch things where the program is effectively a script file without an extension.

But in the case of a foo.95 file, I'm not sure that's appropriate.  Hmmm.

**Comment by CyberShadow** [comment]
Ah, I didn't know PHP supported shebang syntax.

I think an option to control whether ack looks for the shebang line would suffice.
(Alternatively, a regex which specifies which file names to check for shebang lines - the default being files without an extension?)

**Comment by petdance** [comment]
ack2 will let users define how ack sees files, and you can then turn that off if you want.  Everything will live in an ackrc file, and you'll be able to have per-project ackrc files, too.

See https://github.com/petdance/ack2/blob/master/ackrc for what we have so far.

**Comment by CyberShadow** [comment]
Cool, thanks.

Feel free to close this issue if you like, then.

**Comment by petdance** [comment]
I'm going to keep it open as a reminder.  Thanks for bringing this to my attention.

**Comment by petdance** [comment]
This has been optimized away in ack 2.0.
