### ISSUE TITLE
Command line options -l and -1 don't work together

### ISSUE THREAD

**Issue by spaceships** [beyondgrep/ack1#229]
Expected only the first file with a match (from -1), got all.

< bcarmer@trouble ~ > ack -l1 'hello' ~/perl5
/home/bcarmer/perl5/perlbrew/build/perl-5.17.1/Porting/checkAUTHORS.pl
/home/bcarmer/perl5/perlbrew/build/perl-5.17.1/pod/perlinterp.pod
/home/bcarmer/perl5/perlbrew/build/perl-5.17.1/pod/perlfilter.pod
/home/bcarmer/perl5/perlbrew/build/perl-5.17.1/pod/perl5005delta.pod
/home/bcarmer/perl5/perlbrew/build/perl-5.17.1/pod/perldtrace.pod
/home/bcarmer/perl5/perlbrew/build/perl-5.17.1/pod/perlfunc.pod
/home/bcarmer/perl5/perlbrew/build/perl-5.17.1/pod/perlport.pod
/home/bcarmer/perl5/perlbrew/build/perl-5.17.1/pod/perldiag.pod
/home/bcarmer/perl5/perlbrew/build/perl-5.17.1/pod/perltoc.pod
/home/bcarmer/perl5/perlbrew/build/perl-5.17.1/pod/perltrap.pod
/home/bcarmer/perl5/perlbrew/build/perl-5.17.1/pod/perltie.pod
....etc

**Comment by petdance** [comment]
I don't know if we'll fix this in ack 1, but it's also a bug in ack 2.x so I am copying the bug over there.

https://github.com/petdance/ack2/issues/133

**Comment by hoelzro** [comment]
Closed, as the ack2 issue is closed.
