### ISSUE TITLE
Add an option to print null byte after filename in --nogroup listings

### ISSUE THREAD

**Issue by nathansobo** [beyondgrep/ack1#230]
Grep offers the -Z / --null option to print a null byte instead of a ':' after the file name and before the line number in a listing. This allows for filenames with both : characters and newlines to be handled gracefully by looking for a null byte instead of a newline before parsing the line number.

I hacked this in by changing the `print_match_or_context` function as follows:

``` perl
    my $sep = $is_match ? "\0" : '-';
```

But I don't really know Perl and how this option should fit into the grander scheme. Perhaps the -print0 option could be extended to cover this case as well?

**Comment by petdance** [comment]
An interesting idea.  Seems to me that where this is really going is a CSV-ish general output format.  Over on ack2 (where this would get added if we added it) we've been talking about JSON output.  Same sort of idea.

**Comment by nathansobo** [comment]
JSON would be good too, actually. Anything to help make the output easily machine-readable would be great. Including match locations (line number, column, array of match, subgroup matches) in the JSON output would be a double-win. I'll check out ack2.
