### ISSUE TITLE
Support for ignorelist stored in file

### ISSUE THREAD

**Issue by virhilo** [beyondgrep/ack1#232]
It would be nice for ack to support list of ignored directories stored in file like .gitignore or .hgignore, for example you have directories that you always want to ignore and these are different for different projects so it 'll be usefull to have file like .ackignore per directory:)

**Comment by petdance** [comment]
Thanks. This won't happen with ack 1.x, but could in ack 2.  Moved to the ack2 queue. https://github.com/petdance/ack2/issues/144

**Comment by virhilo** [comment]
Thanks
