### ISSUE TITLE
Fwd: Inconsistency between man page and help

### ISSUE THREAD

**Issue by cheese** [beyondgrep/ack1#233]
Original report: https://bugzilla.redhat.com/show_bug.cgi?id=856280

Description of problem:
Some options present in help are not in man:
- --break --nobreak
- --heading --noheading
- --help-types
- --invert-file-match
- --nopager

In man, long option to -a is --all, in help it is --all-types.
In help, --env is missing.

Version-Release number of selected component (if applicable):
ack-1.96-6.fc18.noarch

How reproducible:
Always

Steps to Reproduce:
1. Check man page
2. Check --help option

Actual results:
Inconsistent man page/help

Expected results:
Consistent man page/help

**Comment by petdance** [comment]
Thanks.  We probably won't fix this in ack 1.x, but it's now in the ack 2 queue.

https://github.com/petdance/ack2/issues/150
