### ISSUE TITLE
ack 2.0 -a

### ISSUE THREAD

**Issue by rking** [beyondgrep/ack1#235]
I feel dumb, but:

```
% ack -a xyz
Option '-a' is not valid in ack 2
```

Huh?

**Comment by petdance** [comment]
See the discussion of incompatibilities at https://github.com/petdance/ack2

`Removed the -a and -u options since the default is to search all text files.`

**Comment by rking** [comment]
Not sure if I like this. I am on my phone so I don't want to tap out the whole sentiment, but can you please point me to some docs/discussion about this decision?

**Comment by petdance** [comment]
It's been discussed on the ack-users mailing list, probably around April or May.

**Comment by rking** [comment]
Well, here's what I do know:

In ack 1 you don't get `tags` files or Rails `log/*.log` output intermingled unless you `-a`.  Granted, it also (annoyingly) leaves out extensionless files by default, but I am at least one user who had a groove going.

Now, in ack 2, you get a giant flood.

**Comment by petdance** [comment]
ack 2 also has a -k/--known-types which makes it only select files of known types, rather than any text file, which is the behavior of ack 1.x.  You can add it to you ackrc just like any other option.

**Comment by rking** [comment]
OK! Now we're getting somewhere!

**Comment by petdance** [comment]
Stuff like this is better discussed on the ack-users list.  Everything we've done in ack 2.0 is based on user input, and we'd glad to have yours.
