### ISSUE TITLE
avoid reading from pipe/FIFO

### ISSUE THREAD

**Issue by powerman** [beyondgrep/ack1#243]
When current directory or it subdirectories contain "named pipe/FIFO" files ack will hang (probably trying to read from them) on any operation, including `ack -f`. Such files can be easily detected using perl's -p file test operator and should be ignored by ack.

Real use case when if happens: we use runit (service supervisor app) to run services (like logger or fastcgi) in our projects, so every project contain subdir with services, and each service directory contain few named pipe files used by supervisor.

**Comment by hoelzro** [comment]
This has been fixed in ack2.
