### ISSUE TITLE
Please include full license text in the distribution

### ISSUE THREAD

**Issue by cheese** [beyondgrep/ack1#245]
That would be a good practice for FOSS and will make packagers happy.

Also please do for File::Next.

**Comment by petdance** [comment]
Why do you see that as preferable to pointing to the URL?

**Comment by cheese** [comment]
That's not a kind of preference. That's just more usual and even always done in any mature project.

After that, it is a responsibility for Fedora packager to convince upstream authors to include full license text.

**Comment by petdance** [comment]
You have given zero reasons why including the text is better than pointing at a website.  Just saying "That's how everyone else does it" is not reason enough for me to do so.

**Comment by cheese** [comment]
This point is also commented in perlmodstyle[1]. After all, at your best judgement.

[1] http://search.cpan.org/~drolsky/perl/pod/perlmodstyle.pod#Licensing

**Comment by petdance** [comment]
> Make sure that your module has a license, and that the full text of it is included in the distribution (unless it's a common one and the terms of the license don't require you to include it).

Artistic 2.0 is common and the terms don't require me to include it.

My judgment, since nobody has said why it's a good thing to include the license, is to not bother to do so.

**Comment by cheese** [comment]
We would respect your decision.

**Comment by petdance** [comment]
Who is "we"?

**Comment by petdance** [comment]
Are you a Fedora packager?  Are you asking for the license text to be included for the benefit of the Fedora project?

**Comment by cheese** [comment]
Relax. That's not a big deal. I am a Fedora packager, but nothing would specially benefit Fedora.

**Comment by petdance** [comment]
I'm relaxed.  I'm just trying to understand.

**Comment by cheese** [comment]
I am not a legal prof and also don't quite understand. Just including full license text is a usual software distributing practice. 

If just referring to a URL, and the page content of the URL changed for some reason (e.g. by intrusion), then the licensing of your software seems changed. Since if just referring to a URL, you are saying "the license of this software is whatever shown on that page". That would be not strict. It would be safe if include full license text.

**Comment by petdance** [comment]
> Just including full license text is a usual software distributing practice.

The point I'm trying to make is that "usual practice" isn't reason enough to do something.

**Comment by petdance** [comment]
There will probably be no further releases of ack 1.x.  However, ack 2.0 now includes an explicit license file.

https://github.com/petdance/ack2/blob/master/LICENSE.md
