### ISSUE TITLE
-L should list files without matches, but it doesn't.

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#249]
`-L` is supposed to print files without matches.

```
   −L, −−files−without−matches
       Only print the filenames of files that do NOT match. This is
       equivalent to specifying −l and −v.
```

However, this is wrong.  `-l -v` actually prints files that have at least one non-matching line, and not what we want `-L` to do, which is to print files that have only non-matching lines.

This needs a fix and a test, although chances are this will not get fixed in ack 1.x.  I've added it as a ticket to the ack2 project.  https://github.com/petdance/ack2/issues/210

Originally reported by Seungbeom Kim musiphil@bawi.org

**Comment by hoelzro** [comment]
This has been taken care of in ack2.
