### ISSUE TITLE
Where can I get the ack 2.0 from this repo? 

### ISSUE THREAD

**Issue by ghost** [beyondgrep/ack1#255]
Hi, where can I get the ack 2.0 from this repo. I intend to update homebrew formula with the latest ack :)

**Comment by petdance** [comment]
I would prefer that people not treat URLs on the website as an API to install the single-file version of ack.  I can't guarantee non-breakage.

How does homebrew know what version it's installing?  It seems to me that if it's always been downloading ack-standalone and installing it that it can't tell what version it is.  How is that possible?

**Comment by ghost** [comment]
Due to what I see at the moment, homebrew seems  to not care the old version of one package. And if we need to do so, it requires a bit hard work 
http://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula

About the version of which package, homebrew just finds the best way to find the right stable package for an app. Normally, it's always the best to have a git repo but if there isn't, the workaround is a link to binary package. 

Homebrew itself owns by the community so the popular packages will be get notified and updated as soon as they find breakable links or something breaking the installation :)

**Comment by hoelzro** [comment]
I'm closing this, as it's stagnant and the ack2 formula has already been submitted to Homebrew.
