### ISSUE TITLE
docs still suggest `-a` in v2.04

### ISSUE THREAD

**Issue by rjbs** [beyondgrep/ack1#256]
From the FAQ section:

> Probably because it's of a type that ack doesn't recognize. ack's searching behavior is
> driven by filetype. If ack doesn't know what kind of file it is, ack ignores the file.
> Use the -f switch to see a list of files that ack will search for you.
> If you want ack to search files that it doesn't recognize, use **the -a switch.**

**Comment by petdance** [comment]
Thanks, this has been removed in ack 2.0.

Also, the ack2 repo is https://github.com/petdance/ack2/

**Comment by hoelzro** [comment]
I've moved this to the ack2 queue: https://github.com/petdance/ack2/issues/325
