### ISSUE TITLE
Add notice to ack's Github page to look at ack repo

### ISSUE THREAD

**Issue by hoelzro** [beyondgrep/ack1#265]
The project description should mention the ack2 repo, or we should merge them, or something.

**Comment by hoelzro** [comment]
Also: the issues for ack should be made read-only or something.

**Comment by dolmen** [comment]
Committing a CONTRIBUTING.{md,pod} file in the repo could be a good way of telling users to NOT contribute to this repo (just in case the README is not enough).

**Comment by petdance** [comment]
Already put a notice on it.  Thansk.
