### ISSUE TITLE
Docs: .ackrc example is unclear about --type-add and --type-set

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#42]
The documentation is missing one special case when describing th .ackrc
file. It's not obvious that two = sings are needed to get that case to work.

This is a patch that modifies the docs to show an example of that case.

Thanks for an incredibly useful piece of software. (And for adding this
feature that I had not yet gotten around to asking for.)

G. Wade

Reported by wjohn...@anomaly.org at 2008-04-02 00:35:SImported from Google Code issue number 78

**Comment by petdance** [comment]
Also, since each line of .ackrc becomes one element of @ARGC, you can use:
--type-add
newtype=.ext1,.ext2

which will also work.

-- michael.bracewell, 2008-04-14 23:00:14

**Comment by petdance** [comment]
Duplicate of <a href="/p/ack/issues/detail?id=80" class="closed_ref" title="Cannot use --type-add and type-set in .ackrc following the suggestion in ack --man"> Issue 80 </a>, see there.

-- torsten.blix, 2008-05-09 01:47:43

**Comment by lorin** [comment]
I ran into this issue as well. I would be happy to document this if you could point me in the right place to do so.

Tthe issue 80 link in the comment above https://github.com/p/ack/issues/detail?id=80 is broken, and https://github.com/petdance/ack/issues/80 appears unrelated.

**Comment by petdance** [comment]
It should be documented already in the man page or in `ack --man` under "Defining your own types."  Do you not have that section?  Are you on an old version of ack?

**Comment by lorin** [comment]
I'm running 1.96, and it is actually in the man page, but I'm more likely to look online than at my local documentation...

I was referring to http://betterthangrep.com/documentation, which is where I turned first.  Can we get it added there, or a pointer to somewhere else online?

**Comment by petdance** [comment]
Aha, hadn't thought of that.  I've added an issue addressing the need for the docs online at https://github.com/petdance/betterthangrep/issues/16
