### ISSUE TITLE
Problem with specifying regex for ack -g

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#77]
Reported by torsten.blix, Dec 14, 2007

What steps will reproduce the problem?
$ ack --text -g of t/text/
t/text/4th-of-july.txt
t/text/freedom-of-choice.txt
t/text/science-of-myth.txt
$ ack --text -g=of t/text/
$

What is the expected output? What do you see instead?
The 2nd command (-g=of) should produce the same output as the first (-g of)
but produces no output instead.

The 2nd command - not working - is the documented form as of 'ack --help'.

I think this is a Getopt::Long 'feature' in connection with the
configuration option 'bundling' (which ack uses). If you change the option
to '--g=of' then it works again. '-g=of' instead gives '=of' as the value
for the option 'g'. This is documented in the code of Getopt::Long (not in
the documentation, though).

Alternatives for fixing this are:
1) Change the doc for ack.
2) Don't use the Getopt::Long 'bundling' option.
3) Fix(?)/Change Getopt::Long

of which only alternative 1 seems reasonable to me

**Comment by hoelzro** [comment]
Migrated to ack2 queue.
