### ISSUE TITLE
Global ackrc support

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#79]
Instead of having to maintain many .ackrc files to --type-add and --type-
set the file types used in our company, I'd like to see support for 
a .ackrc stack

./.ackrc                 <- most important
~/.ackrc
/usr/local/etc/ack.rc
/etc/ack.rc              <- least important

or something similar

**Comment by petdance** [comment]
This will be required for Ack 2.0

**Comment by elpargo** [comment]
+1

**Comment by madsen** [comment]
Ack 2 currently looks for `/etc/ackrc`, but not `/usr/local/etc/ackrc`.  I can see loading both being useful (distro config vs. local config).  Should we change it to look for both?

**Comment by petdance** [comment]
I don't think we can go down that road.  Then we'll be looking `/opt/local/etc/ackrc` and who knows what else?

**Comment by karenetheridge** [comment]
only one $SYSTEM/ackrc need be looked for in this stack, where $SYSTEM is defined at installation time. If ack is installed into /usr/bin/ack, then look at /etc/ackrc. If installed into /usr/local/bin/ack, look for /usr/local/etc/ackrc; /opt/local/bin/ack -> /opt/local/etc/ackrc and so on.

**Comment by petdance** [comment]
@karenetheridge So how do we do that?  Is there something in ExtUtils::MakeMaker that specifies that?

What about for packaged versions that aren't done with EU:MM?  And what do we do for the standalone version where people install it themselves?

**Comment by karenetheridge** [comment]
@petdance I mean that the script would look at what path it was installed into (/usr/bin, /usr/local/bin, ~/perl5/perlbrew/perls/perl-5.22.0/bin etc) and uses that base path as a means to find the associated rc file. EUMM doesn't get involved at all.

**Comment by petdance** [comment]
This is in ack 2 now.
