### ISSUE TITLE
Add a - or --stdin option for compatibilty with grep

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#85]
Reported by krawczyk, Oct 07, 2008

"ack pattern -" tries to read a file called "-" instead of STDIN.

It should force STDIN to be used instead, as grep does.

Comment 1 by petdance, Oct 07, 2008

(No comment was entered for this change.)

Status: Accepted
Labels: -Priority-Medium Priority-High
Delete comment
Comment 2 by petdance, Oct 07, 2008

(No comment was entered for this change.)

Labels: -Priority-High Priority-Critical
Delete comment
Comment 3 by shlomif, Oct 10, 2008

This patch fixes this problem. I had to do a lot of workaround work because of the
Ack architecture. I didn't include any tests unique to this change, because I didn't
know  how to test it well. But it passes all existing tests.

```
ack-issue-103-fix.patch     
```

9.6 KB Download
Delete comment
Comment 4 by shlomif, Oct 10, 2008

After some commentary from petdance on IRC, he told me not to implement it using the
App::Ack::_Iterator. I tried to remove it now, but as it turns out, the call to
File::Next::files() doesn't handle the "-" correctly:

<<<<<<<<<<<
sub files {
    my ($parms,@queue) = _setup( \%files_defaults, @_ );
    my $filter = $parms->{file_filter};

```
return sub {
    while (@queue) {
        my ($dir,$file,$fullpath) = splice( @queue, 0, 3 );
        if ( -f $fullpath ) {
            if ( $filter ) {
                local $_ = $file;
                local $File::Next::dir = $dir;
                local $File::Next::name = $fullpath;
                next if not $filter->();
            }
            return wantarray ? ($dir,$file,$fullpath) : $fullpath;
        }
        elsif ( -d _ ) {
            unshift( @queue, _candidate_files( $parms, $fullpath ) );
        }
    } # while

    return;
}; # iterator
```

}

As can be seen the -f $fullpath and -d _ calls fail and as a result nothing is
returned. So the only way to fix it is to "fix" File::Next.

Delete comment
Comment 5 by petdance, Apr 23, 2009

I'm thinking a --stdin option would be the way to go, a la git.

**Comment by blixtor** [comment]
Is this option then supposed to be exclusive? Meaning, if --stdin is specified, then no other files are read?

And probably it only makes sense in the context of a normal search, e.g. ack --stdin regex and not in conjunction with -f, -g or -l?

**Comment by petdance** [comment]
There are already checks for that.  It's what ack currently calls "filter mode".

**Comment by blixtor** [comment]
I'm not sure I get you.

I know about filter mode. But I think filter mode and input from STDIN are two separate things. It would e.g. be possible to say "ack regex --stdin file1 file2 < file3" and have ack search the 3 given files, two directly and one reading from STDIN (which then doesn't have to be a file, of course).

**Comment by petdance** [comment]
I'm not sure I like the idea of reading from two disk files and from STDIN.  What other utilities handle something like that?

**Comment by blixtor** [comment]
I don't know of any, I'm just trying to understand what this issue is all about ;)

So in your eyes, this issue would be solved by implementing issue 90, a --[no]filter option, to force (or unforce) ack's filter mode? I'd be 100% fine with that. Possibly adding --stdin as a synonym for --filter ...

**Comment by hoelzro** [comment]
This functionality already exists in ack2.
