### ISSUE TITLE
Add a flag to trim large lines

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#86]
It would be nice if ack had a flag such that it trimmed long lines down to
terminal width.  This would especially help with "ack -a" finding files
that don't have newlines in them.

I would suggest --width or --width=80; the former attempting to use the
width of the terminal, if present.  I have no suggestion on how much
context to print on either side if a line needs to be chopped.

I would expect that if my match exceeded the terminal width, to print out
the entire match despite its length.  I have no suggestion on what to do if
a long line matches multiple times.

**Comment by hoelzro** [comment]
Migrated to ack2 queue.
