### ISSUE TITLE
Add .mk for makefile fragments

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#88]
In http://www.gnu.org/software/make/manual/make.html#Makefile-Names,
Makefiles can be GNUmakefile, makefile or Makefile.  Additionally, makefile
fragments are typically put into '.mk' files as seen in
http://www.gnu.org/software/make/manual/make.html#Include

**Comment by coke** [comment]
Having .mak as an extension for Makefile fragments would also be spiffy.

**Comment by petdance** [comment]
This will not happen until ack 2.0.

**Comment by trini** [comment]
This appears to be fixed in the changelog, true?

**Comment by petdance** [comment]
This is done in ack 2 now.
