### ISSUE TITLE
ack does not search /proc/mounts properly

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#89]
What steps will reproduce the problem?
1. run "ack --noenv -u shm /proc/mounts"
2. compare to output of "grep shm /proc/mounts"
3. or to output of "cat /proc/mounts | ack shm"

What is the expected output? What do you see instead?

Expect a line containing the string being matched.  What you get, in step
1, is nothing.

What version of the product are you using? On what operating system?

Linux, and ack is 1.86

Please provide any additional information below.

If your /proc/mounts does not (for some other reason) have /dev/shm
mounted, just pick some other string which _does_ appear in /proc/mounts. 
That "shm" is not the important part here; the way ack deals with files in
/proc is the issue.

In fact it doesn't have to be /proc/mounts.  I tried with /proc/meminfo and
the string "Dirty"; same inconsistencies.

**Comment by hoelzro** [comment]
Migrated to ack2 queue.
