### ISSUE TITLE
Handle rakefiles

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#92]
Handle Rakefile (a la Makefile) and .rake.  Make them seen as both --rake
and --ruby, because they are.

Delete comment
Comment 1 by petdance, Jan 17, 2009

From http://elhumidor.blogspot.com/2009/01/ack-in-project-skipping-rake.html

rakefile.rb is also a name to recognize

**Comment by ingmarv** [comment]
Andy, are you planning some generic way to match a file's basename, rather than just the extension?

I could use this for --cmake, which would recognize CMakeLists.txt (basename), and *.cmake (extension)

I'm not sure how to implement this nicely, but given some suggestions, I'd give it a try.

**Comment by petdance** [comment]
This isn't going to happen until ack 2.0.

**Comment by petdance** [comment]
These are handled in ack 2 now.
