### ISSUE TITLE
BTG: Add install notes about Solaris

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#93]
```
From:   skayser@opencsw.org
Subject:    ack: packaged for Solaris and available via opencsw.org
Date:   April 6, 2009 5:48:20 PM CDT
To:     andy@petdance.com
```

Hi Andy,

thanks alot for ack :) Not only is it a neat tool on its own, but also
it made me learn how to tweak grep a bit (in case i don't have ack around).

Just wanted to let you know that i packaged ack so that it is now also
available via opencsw.org for Solaris [1]. Maybe you want to add this to
the list of "How to install ack". Install mechanism is similar to other
packaging tools [2].

 1) Install pkg-get (and optionally adjust mirror)
 2) pkg-get -Ui ack

Let me know in case you might see any issues with the package.

Cheers

Sebastian

[1] http://opencsw.org/packages/ack
[2] http://opencsw.org/pkg-get

**Comment by hoelzro** [comment]
Moved to the beyondgrep queue.
