### ISSUE TITLE
ActivePerl 5.8.8 install problem

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#95]
Win32, ActivePerl 5.8.8. I did not have any problems with Strawberry 5.10.0
and 5.8.8.

t/ack-passthru............
# Failed test 'Got all the lines back'
# at t/ack-passthru.t line 52.
# got: '12323'
# expected: '37'
# Failed test 'Only two lines are highlighted'
# at t/ack-passthru.t line 55.
# got: '9'
# expected: '2'
# Looks like you failed 2 tests of 6.

 Dubious, test returned 2 (wstat 512, 0x200)
 Failed 2/6 subtests

t/context.................
# Failed test 'Only two lines are highlighted'
# at t/context.t line 134.
# got: '89'
# expected: '2'
# Failed test 'Expecting altogether 18 lines back'
# at t/context.t line 135.
# got: '97'
# expected: '18'
# Looks like you failed 2 tests of 22.

 Dubious, test returned 2 (wstat 512, 0x200)
 Failed 2/22 subtests

**Comment by hoelzro** [comment]
If this is still a problem in ack2, it probably already exists in the queue.
