### ISSUE TITLE
UCS-2 encoded file not read by ack

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#96]
Reported by tobyteel, Jun 11, 2009

What steps will reproduce the problem?
1. Create a file encoded in UCS-2 (big endian or little endian).
2. Add a string to the file.
3. Search the directory for the string with ack.  Ack will not find the string.

Note that converting the file to UTF-8 or ANSI fixes the issue.

I used Notepad++ 5.0 to open the file and re-encode it.

What is the expected output? What do you see instead?

Ack does not appear to search the UCS-2 file correctly.  You receive no
results.

What version of the product are you using? On what operating system?

ack 1.86 on (Strawberry) Perl 5.10.0 on Windows Server 2008 (32-bit) (ver
reports Windows 6.0.6001, winver reports Windows 6.0 (build 6001, SP1))

ack was run from the Command prompt.

Delete comment
Comment 1 by tobyteel, Jun 11, 2009

A friend also encountered this bug running ack 1.86 in cygwin under Windows Server
2003 Standard Edition, SP2 with perl 5.10.0 built for cygwin-thread-multi-64int.

Delete comment
Comment 2 by tobyteel, Jun 11, 2009

The above friend was using CYGWIN_NT-5.2 1.5.25(0.156/4/2) 2008-06-12 19:34

**Comment by hoelzro** [comment]
Migrated to ack2 queue.
