### ISSUE TITLE
pipe detection on OS X fails

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#97]
Reported by harryfmudd@comcast.net, Feb 19, 2009

When trying to install App::Ack 1.88 on a Mac OS 10.3.9 (Panther) system
under Perl 5.10.0, I experienced the following test failures.

t/ack-passthru.t .......... 5/6 
# Failed test 'Only two lines are highlighted'
# at t/ack-passthru.t line 55.
# got: '9'
# expected: '2'
# Looks like you failed 1 test of 6.

t/ack-passthru.t .......... Dubious, test returned 1 (wstat 256, 0x100)

t/context.t ............... 13/22 
# Failed test 'Only two lines are highlighted'
# at t/context.t line 134.
# got: '89'
# expected: '2'
# Failed test 'Expecting altogether 18 lines back'
# at t/context.t line 135.
# got: '97'
# expected: '18'

t/context.t ............... 19/22 # Looks like you failed 2 tests of 22.
t/context.t ............... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/22 subtests 

These did not occur under Mac OS 10.5 (Leopard). I did not test 10.4
(Tiger), though I can if need be.

To cut to the chase: the problem seems to be that the two systems give
different results for the -p operator:

Mac OS 10.3.9:

$ cat t/text/4th-of-july.txt | perl -le 'print -p STDIN ? "yes" : "no"'
no
$ cat t/text/4th-of-july.txt | /usr/bin/perl -le 'print -p STDIN ? "yes" :
"no"' 
no
$ 

/usr/bin/perl in this case is 5.8.1-RC3, which I tested to try to
demonstrate whether there was something wrong with my perl build.

Mac OS 10.5.6:

$ cat t/text/4th-of-july.txt | perl -le 'print -p STDIN ? "yes" : "no"'
yes
$ cat t/text/4th-of-july.txt | /usr/bin/perl -le 'print -p STDIN ? "yes" :
"no"' 
yes
$ 

In this case, /usr/bin/perl is 5.8.8.

The net effect is that under Mac OS 10.3 you can't pipe input into 'ack'.
You can not work around this by specifying '-' as the input file name,
though I have not investigated why.

The attached .patch file is a universal diff on the 'ack' script that
appears to solve the problem. Whether you do anything about this is up to
you -- Mac OS 10.3 is fairly old now. But at least the behavior is documented.

**Comment by hoelzro** [comment]
I think this works as of ack 2.
